### ISSUE TITLE
Is it possible to search recursively like original FZF?

### ISSUE THREAD

**Issue by israelg99** [Aloxaf/fzf-tab#233] opened 2021-09-29 12:31 UTC
Is it possible to search recursively like original FZF?

Goal:
![image](https://user-images.githubusercontent.com/2307599/135268650-02395640-86c4-4a5f-9407-fdb70f561f29.png)

`fzf-tab`:
![image](https://user-images.githubusercontent.com/2307599/135268784-a18cb9ee-fc64-43b0-a498-037cb3058e82.png)

**Comment by Quentin-M** [comment] 2022-04-12 18:22
I would also love to have this as it'd make the completion actually be able to use fzf's full potential. It is actually discussed a bit in https://github.com/Aloxaf/fzf-tab/issues/65 where @romkatv mentions he's implemented just that in https://github.com/romkatv/zsh4humans, with files streaming in as they are found, but it is unfortunately extremely tied to it and not easily portable here easily.

**Comment by Aloxaf** [comment] 2022-12-14 06:50
duplicate of https://github.com/Aloxaf/fzf-tab/issues/65

**Closed by Aloxaf** 2022-12-14 06:50 UTC
Labels: question
