### ISSUE TITLE
[Q] Can tab complete to the longest common prefix, then open fzf?

### ISSUE THREAD

**Issue by cohml** [Aloxaf/fzf-tab#402] opened 2023-12-16 15:21 UTC
Given the following directory:

```
$ ls
foo1.txt
foo2.txt
bar.txt
```

Is it possible to modify `zstyle`'s completion behavior such that if I enter

```
$ ls f<tab>
```

_it will complete the command line to_

```
$ ls file
```

and _then_ also open fzf with all the options beginning with `f`, i.e.,

```
file1.txt
file2.txt
```

? Then I'd just have to enter `1` or `2` to make a selection?

This would be a very nice way to communicate what the common prefix is for all items, starting with the substring I entered.

The default behavior just opens fzf without completing the common prefix for me. This means I have to scan the options to determine the prefix, which is more work for me.

Awesome plugin btw 😄

**Comment by Aloxaf** [comment] 2024-02-21 09:42
duplicate of #8

**Closed by Aloxaf** 2024-02-21 09:42 UTC
Labels: question
