### ISSUE TITLE
[BUG] `cd` completion bug when a folder start with digit

### ISSUE THREAD

**Issue by Harrd** [Aloxaf/fzf-tab#465] opened 2024-08-11 04:28 UTC
#### Describe the bug
- `cd` completion add an unexpected digit input  when there is a folder start with digit (in this case `3rd`)

<img width="270" alt="image" src="https://github.com/user-attachments/assets/19047311-7d23-4da1-acf6-9b477734bb63">
<img width="257" alt="image" src="https://github.com/user-attachments/assets/d265a14c-74ed-4459-8151-bd74170e3fd5">

- mv `3rd ` to `third`(without digit), bug will be fixed
<img width="208" alt="image" src="https://github.com/user-attachments/assets/d78fccb5-2f87-4906-8abc-495c7135af00">

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
- rename a folder begin with digit and try use `cd` with tab

#### Expected behavior
- no extra digit

#### Environment:
 - OS: MacOS 14.5
 - zsh version: 4.9

**Comment by xkoldxx** [comment] 2024-10-14 22:24
i have stipped all completion config besides the config in the setup page removed all plugins and the issue is still present brew seems to take completion from somewhere else

**Comment by Aloxaf** [comment] 2024-11-07 00:52
duplicate of https://github.com/Aloxaf/fzf-tab/issues/264 https://github.com/Aloxaf/fzf-tab/issues/327.

please install zsh with pcre support.

**Closed by Aloxaf** 2024-11-07 00:52 UTC
Labels: bug
