### ISSUE TITLE
[BUG] Faulty completion when completing `networkctl`

### ISSUE THREAD

**Issue by rouven0** [Aloxaf/fzf-tab#428] opened 2024-04-11 09:36 UTC
#### Describe the bug
When completing systemd-networkd's `networkctl` command, interface names aren't completed correctly. When choosing a proposed completion, the whole line of completion with all its attributes is pasted instead of just the interface name.

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting. (Error still occurs if these are disabled)

#### To Reproduce
1. Type 'networkctl status '
2. Select an interface while completing
3. Press <kbd>Tab</kbd>

#### Expected behavior
Only the interface name is completed. Without the extra attributes shown in the completion.

#### Screenshots
![image](https://github.com/Aloxaf/fzf-tab/assets/72568063/47d99827-ac45-4b11-9d35-27bd597ca2f3)
![image](https://github.com/Aloxaf/fzf-tab/assets/72568063/fa8133b5-6ea3-48f3-86a4-7c4d4e123763)

#### Environment:
 - OS: NixOS unstable
 - zsh version: 5.9

**Comment by Aloxaf** [comment] 2024-04-24 00:47
duplicate of https://github.com/Aloxaf/fzf-tab/issues/424

**Closed by Aloxaf** 2024-04-24 00:47 UTC
Labels: bug
