### ISSUE TITLE
[Q] why my completion is like this

### ISSUE THREAD

**Issue by fabioluciano** [Aloxaf/fzf-tab#449] opened 2024-06-14 03:12 UTC
After a update, my completions looks like this and i cant fix

![image](https://github.com/Aloxaf/fzf-tab/assets/499057/ffecbec4-f21b-411c-aa1d-02fa1ef3d55d)

**Comment by petricavalry** [comment] 2024-11-05 14:28
Thanks for reporting this. Please provide your configuration file.

**Comment by Aloxaf** [comment] 2024-11-06 07:31
duplicate of https://github.com/Aloxaf/fzf-tab/issues/24#issuecomment-574986122

**Closed by Aloxaf** 2024-11-06 07:31 UTC
Labels: question
