### ISSUE TITLE
[BUG] --color=fg:*,fg+:* is not respected, but works in fzf

### ISSUE THREAD

**Issue by egirlcatnip** [Aloxaf/fzf-tab#477] opened 2024-10-03 13:24 UTC
#### Describe the bug

I can make sure:
- [x] I am using the latest version of fzf-tab
- [x] this is the minimal zshrc which can reproduce this bug
- [x] fzf-tab is loaded after `compinit`
- [x] fzf-tab is loaded after plugins which will wrap <kbd>Tab</kbd>, like [junegunn/fzf/completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
- [x] fzf-tab is loaded before zsh-autosuggestions, zsh-syntax-highlighting and fast-syntax-highlighting.

#### To Reproduce
1. set ``zstyle ':fzf-tab:*' fzf-flags --color=fg:5``
2. compare to command ``fzf --color=fg:5``

#### Expected behavior
fg and fg+ color is respected in the configuration. This way, in gnome's light mode, the foreground is hard to read.

#### Screenshots
Bug:
![image](https://github.com/user-attachments/assets/90fc4195-692e-46ce-ae64-255bf1efce97)
Expected:
![image](https://github.com/user-attachments/assets/b3775555-cc01-4c4a-b08b-4cc12ab2920a)

#### Environment:
 - OS: Fedora 40
 - zsh version: 5.9

**Comment by zhermin** [comment] 2024-10-04 17:13
Same here, tried a few combinations of `zstyle` flags and location in `.zshrc` and following the README but the colors don't persist.

**Comment by Aloxaf** [comment] 2024-10-09 17:50
@pivoshenko your problem is a duplicate of #475

**Comment by Aloxaf** [comment] 2024-10-09 18:05
This is strange, I cannot reproduce this. fzf-flags is appended to the end of the fzf commandline, it should work. 

Can you make sure you only set `fzf-flags` once? And please provide the log (trigger fzf-tab with `Ctrl-x .`).

**Comment by pablospe** [comment] 2024-10-09 22:05
> ```shell
> --color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796
> ```

Could you try adding `'` (single quote) like this:
`--color='bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796'`

**Comment by peterldowns** [comment] 2024-11-01 19:40
@egirlcatnip I was having this issue as well — no matter what I did, the foreground text color was ALWAYS "white". After messing around debugging in the source of fzf-tab, I believe the issue is due to the default "group color":

https://github.com/Aloxaf/fzf-tab/blob/b6e1b22458a131f835c6fe65bdb88eb45093d2d2/lib/-ftb-generate-complist#L12

```zsh
-ftb-zstyle -s default-color default_color || default_color=$'\x1b[37m'
```

which defaults to `Esc[37m`, which is "dark white" https://ss64.com/nt/syntax-ansi.html.

You can tell if this is the issue by triggering a fzf-tab completion list, then changing your terminal color settings and seeing if it updates.

I was able to fix this problem and configure fzf-tab to completely respect my fzf colors by changing this color to `""` (empty string) by adding this to my `~/.zshrc`:

```zsh
zstyle ':fzf-tab:*' default-color ""
zstyle ':fzf-tab:*' use-fzf-default-opts yes
source ~/.zsh/plugins/fzf-tab/fzf-tab.plugin.zsh
```

This is one of the most frustrating bugs I've recently encountered. I don't understand what the purpose is of the "groups" stuff at all.

**Comment by villem** [comment] 2024-11-04 14:02
...
> This is one of the most frustrating bugs I've recently encountered. I don't understand what the purpose is of the "groups" stuff at all.

I spent some time with this one too. Your fix works with my wezterm well too. Thank you for finding the workaround!!

**Comment by peterldowns** [comment] 2024-11-05 15:42
@villem ah, now I notice it too. The reason is that fzf-tab hardcodes `--color=hl:...` in the flags it passes:

https://github.com/Aloxaf/fzf-tab/blob/b6e1b22458a131f835c6fe65bdb88eb45093d2d2/lib/-ftb-fzf#L94

And because it does this explicitly, it takes precedence over the flags passed via`FZF_DEFAULT_OPTS`. You can work around this by passing your flags explicitly via the `fzf-flags` zstyle setting, since those flags are passed at the end of invoking `fzf`:

https://github.com/Aloxaf/fzf-tab/blob/b6e1b22458a131f835c6fe65bdb88eb45093d2d2/lib/-ftb-fzf#L107

```zsh
zstyle ':fzf-tab:*' fzf-flags --color=hl:...
```

I'm going to send a PR to this repo to remove these styling settings. I don't understand why they're coded this way.

**Comment by villem** [comment] 2024-11-06 05:49
The patches works great!! I left comment to pull request too.

**Closed** 2024-11-07 00:37 UTC
Labels: bug
