### ISSUE TITLE
[Q]can not preview the image in fzf's preview window

### ISSUE THREAD

**Issue by tiancheng92** [Aloxaf/fzf-tab#333] opened 2022-12-06 09:45 UTC
I can not preview the image in fzf's preview window

![截图2022-12-06 17-40-02@1x](https://user-images.githubusercontent.com/42594679/205876193-3c2cc9f8-a1ea-4731-aa4c-70f87a46fc6e.jpg)

I use wezterm zsh5.9

```bash
# fzf-tab预览
_preview()
{
    local file="$1"
    if [[ -d "${file}" ]] || [[ -h "${file}" ]]; then
        lsd -A --tree --depth 1 "${file}"
    elif [[ -f "${file}" ]]; then
        local info="$(file "${file}")"
        if [[ "${file}" == *.md ]]; then
            mdcat -l ${file}
        elif [[ "${file}" == *.pdf ]];then
            pdftotext ${file} -
        elif [[ "${info}" == *text* ]]; then
            bat "${file}" 2> /dev/null
        elif [[ "${info}" == *image\ data* ]]; then
            chafa "$1"
            exiftool "$1"
        else
            builtin echo "${info}"
        fi
    else
        builtin echo "${file}" | lolcat -f
    fi
}

```

**Comment by Aloxaf** [comment] 2022-12-07 02:58
duplicate of https://github.com/Aloxaf/fzf-tab/issues/303

And th preview function is provided by fzf, I can do nothing with it.

**Closed by Aloxaf** 2022-12-07 02:58 UTC
Labels: question
